[tool.poetry]
name = "moatless"
version = "0.0.2"
description = ""
authors = ["Albert Örwall <albert@moatless.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
pydantic = "2.7.4"  # Prevent the buggy 2.8.0b1 prerelease

datasets = "2.19.0"

litellm = "1.40.17"
instructor = "1.3.3"
tiktoken = "0.7.0"
networkx = "3.3"

tenacity = "8.5.0"

tree-sitter = "0.22.3"
tree-sitter-python = [
  {platform = "linux", version = "0.21.0"},
  {platform = "darwin", git = "https://github.com/tree-sitter/tree-sitter-python"}
]
tree-sitter-java = "0.21.0"

rapidfuzz = "3.9.3"

openai = "1.34.0"
anthropic = "0.29.0"

llama-index = "0.10.45"
llama-index-embeddings-openai = "0.1.10"
llama-index-embeddings-voyageai = "0.1.4"
llama-index-readers-file = "0.1.25"

jsonref = "1.1.0"
pylint = "3.2.3"

numpy = "1.26.4"
scipy = "1.13.1"
faiss-cpu = "1.8.0"

pyarrow = "14.0.2"
requests =  "2.31.0"
pandas = "2.0.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-mock = "3.14.0"
python-dotenv = "1.0.1"
mypy = "1.10.0"
ruff = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"
extend-exclude = ["tests", "evaluations", "notebooks"]

[tool.ruff.lint]
select = [
  "B",     # Bugbear
  "DTZ",   # Datetimes
  "E",     # Pydocstyle
  "F",     # Pyflakes
  "I",     # Import order
  "LOG",   # Logging
  "N",     # Naming (PEP8)
  "PLE",   # Pylint errors
  # "PTH",   # Pathlib
  "SIM",   # Simplify
  "T20",   # Print statements
  "UP",    # Pyupgrade
]
ignore = [
  "E501",   # Line too long
  "F401",   # Unused import
]
